source "https://rubygems.org"

gem 'sinatra', '~> 2.2', '>= 2.2.2'

gem 'activerecord', '~> 7.0', '>= 7.0.3.1'

gem 'sqlite3', '~> 1.4', '>= 1.4.4'

gem 'rake', '~> 13.0', '>= 13.0.6'

gem 'sinatra-activerecord', '~> 2.0', '>= 2.0.25'

gem 'require_all'

gem 'puma'

group :development do
    gem "rerun"
end

# These gems will only be used when we are running the application locally
group :development do
  gem "pry"
end

# These gems will only be used when we are running tests
group :development do
  gem "database_cleaner"
  gem "rspec"
end

gem "ruby-lsp", "~> 0.3.0", :group => :development
