source 'https://rubygems.org/'

gem 'rake', '~> 13.0', '>= 13.0.6'
gem 'activerecord', '~> 7.0', '>= 7.0.3.1'
gem 'sinatra', '~> 2.2', '>= 2.2.2', require: 'sinatra/base'
gem 'sinatra-activerecord', '~> 2.0', '>= 2.0.25', require: false
gem 'sinatra-contrib', require: false
gem 'sqlite3', '~> 1.4', '>= 1.4.4'
gem 'require_all', '~> 3.0'
gem 'json', '~> 2.6', '>= 2.6.2'
gem 'dotenv', '~> 2.8', '>= 2.8.1'
gem 'sinatra-reloader', '~> 1.0'

group :development do
    gem 'pry'
end

group :test do
    gem 'database_cleaner'
    gem 'rspec'
end
